# Generated by Django 3.2.7 on 2021-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.TextField(blank=True, db_column='Lab', null=True)),
                ('testcode', models.TextField(blank=True, db_column='TestCode', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('addnames', models.TextField(blank=True, db_column='AddNames', null=True)),
                ('paneldetails', models.TextField(blank=True, db_column='PanelDetails', null=True)),
                ('panelnames', models.TextField(blank=True, db_column='PanelNames', null=True)),
                ('posttests', models.TextField(blank=True, db_column='PostTests', null=True)),
                ('preparment', models.TextField(blank=True, db_column='Preparment', null=True)),
                ('kind', models.TextField(blank=True, db_column='Kind', null=True)),
                ('limitations', models.TextField(blank=True, db_column='Limitations', null=True)),
                ('vessel', models.TextField(blank=True, db_column='Vessel', null=True)),
                ('color', models.TextField(blank=True, db_column='Color', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
                ('bloodamount', models.TextField(blank=True, db_column='BloodAmount', null=True)),
                ('pretransportconditions', models.TextField(blank=True, db_column='PreTransportConditions', null=True)),
                ('transportconditions', models.TextField(blank=True, db_column='TransportConditions', null=True)),
                ('maxtime', models.TextField(blank=True, db_column='MaxTime', null=True)),
                ('addressee', models.TextField(blank=True, db_column='Addressee', null=True)),
                ('testpurpose', models.TextField(blank=True, db_column='TestPurpose', null=True)),
                ('clinicalinfo', models.TextField(blank=True, db_column='ClinicalInfo', null=True)),
                ('method', models.TextField(blank=True, db_column='Method', null=True)),
                ('processingtime', models.TextField(blank=True, db_column='ProcessingTime', null=True)),
                ('specialdays', models.TextField(blank=True, db_column='SpecialDays', null=True)),
                ('outtermonitoring', models.TextField(blank=True, db_column='OutterMonitoring', null=True)),
                ('pricecode', models.TextField(blank=True, db_column='PriceCode', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
        ),
    ]
