# Generated by Django 3.2.7 on 2021-09-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCatalog', '0002_test_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lab_name',
        ),
    ]
