# Generated by Django 4.0.6 on 2022-07-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCatalog', '0003_remove_test_lab_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'מעבדה', 'verbose_name_plural': 'מעבדות'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'בדיקה', 'verbose_name_plural': 'בדיקות'},
        ),
        migrations.AlterField(
            model_name='test',
            name='addnames',
            field=models.TextField(blank=True, db_column='AddNames', null=True, verbose_name='שמות נוספים לבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='addressee',
            field=models.TextField(blank=True, db_column='Addressee', null=True, verbose_name='מען למשלוח בדיקות'),
        ),
        migrations.AlterField(
            model_name='test',
            name='bloodamount',
            field=models.TextField(blank=True, db_column='BloodAmount', null=True, verbose_name='נפח דם נדרש למקבצי בדיקות שונים'),
        ),
        migrations.AlterField(
            model_name='test',
            name='clinicalinfo',
            field=models.TextField(blank=True, db_column='ClinicalInfo', null=True, verbose_name='מידע קליני'),
        ),
        migrations.AlterField(
            model_name='test',
            name='color',
            field=models.TextField(blank=True, db_column='Color', null=True, verbose_name='צבע פקק '),
        ),
        migrations.AlterField(
            model_name='test',
            name='comments',
            field=models.TextField(blank=True, db_column='Comments', null=True, verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='test',
            name='kind',
            field=models.TextField(blank=True, db_column='Kind', null=True, verbose_name='סוג הדגימה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lab',
            field=models.ForeignKey(blank=True, db_column='Lab_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TestCatalog.lab', verbose_name='המעבדה המבצעת'),
        ),
        migrations.AlterField(
            model_name='test',
            name='limitations',
            field=models.TextField(blank=True, db_column='Limitations', null=True, verbose_name='מגבלות הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='maxtime',
            field=models.TextField(blank=True, db_column='MaxTime', null=True, verbose_name='זמן מירבי מדיגום עד הגעה למעבדה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='method',
            field=models.TextField(blank=True, db_column='Method', null=True, verbose_name='שיטת ביצוע הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True, verbose_name='שם הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='outtermonitoring',
            field=models.TextField(blank=True, db_column='OutterMonitoring', null=True, verbose_name='בקרת איכות חיצונית'),
        ),
        migrations.AlterField(
            model_name='test',
            name='paneldetails',
            field=models.TextField(blank=True, db_column='PanelDetails', null=True, verbose_name='פירוט הפאנל: קוד הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='panelnames',
            field=models.TextField(blank=True, db_column='PanelNames', null=True, verbose_name='פירוט הפאנל: שם הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='posttests',
            field=models.TextField(blank=True, db_column='PostTests', null=True, verbose_name='פירוט בדיקות המשך'),
        ),
        migrations.AlterField(
            model_name='test',
            name='preparment',
            field=models.TextField(blank=True, db_column='Preparment', null=True, verbose_name='הכנת החולה לפני הדיגום'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pretransportconditions',
            field=models.TextField(blank=True, db_column='PreTransportConditions', null=True, verbose_name='תנאי לקיחה ושימור טרם שינוע'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricecode',
            field=models.TextField(blank=True, db_column='PriceCode', null=True, verbose_name='קוד מחיר משרד הבריאות'),
        ),
        migrations.AlterField(
            model_name='test',
            name='processingtime',
            field=models.TextField(blank=True, db_column='ProcessingTime', null=True, verbose_name='משך הזמן מקבלת הדגימה ועד הפצת תשובה '),
        ),
        migrations.AlterField(
            model_name='test',
            name='specialdays',
            field=models.TextField(blank=True, db_column='SpecialDays', null=True, verbose_name='האם הבדיקה מבוצעת גם בערבים וסופ"ש? '),
        ),
        migrations.AlterField(
            model_name='test',
            name='testcode',
            field=models.TextField(blank=True, db_column='TestCode', null=True, verbose_name='קוד ביצוע הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testpurpose',
            field=models.TextField(blank=True, db_column='TestPurpose', null=True, verbose_name='מטרת הבדיקה'),
        ),
        migrations.AlterField(
            model_name='test',
            name='transportconditions',
            field=models.TextField(blank=True, db_column='TransportConditions', null=True, verbose_name='תנאי שינוע'),
        ),
        migrations.AlterField(
            model_name='test',
            name='vessel',
            field=models.TextField(blank=True, db_column='Vessel', null=True, verbose_name='כלי קיבול לדגימה '),
        ),
        migrations.AlterField(
            model_name='test',
            name='volume',
            field=models.TextField(blank=True, db_column='Volume', null=True, verbose_name='נפח דגימה מינימלי נדרש'),
        ),
    ]
